### ISSUE TITLE
Runner AI Refuses to make obvious game-winning run.

### ISSUE THREAD

**Issue by GreatA1exander** [bobtheuberfish/chiriboga#131] opened 2023-04-01 08:52 UTC
Game came down to both of us having ~50 credits, 6 agenda points each and a scoring remote with ~7 ice. The runner can definitely get in and steal, but just takes credits forever instead.

It also seems to suspect that I have no agendas in HQ, despite having multiple with a known deck of just marilyn campaign. Not sure where else to start debugging.

[chiriboga-log-2023-04-01T08_48_47.348Z.txt](https://github.com/bobtheuberfish/chiriboga/files/11128845/chiriboga-log-2023-04-01T08_48_47.348Z.txt)

**Comment by bobtheuberfish** [comment] 2023-04-01 12:45
Thank you for this report and for including the log. The AI's estimation of what's in hand doesn't consider how many agendas are left in the game and/or R&D. There's also some issues with the AI here because your remote server has so much ice that the AI is unable to determine the run cost. You may have noticed it was taking a long time to think each move - the log shows it was taking so long thinking about it that it gave up.
I'll investigate both aspects of this issue.

**Comment by bobtheuberfish** [comment] 2023-07-08 01:36
This is now fixed in the dev version. 
https://chiriboga.sifnt.net.au/dev/

The simple version of the issue is that the Runner was planning to draw more cards in case there were unrezzed killers, when it should have been planning to use credits with Echelon instead. This is now improved.

**Closed as completed by bobtheuberfish** 2023-07-08 01:36 UTC
Labels: needs investigation
